server:
  port: 8000
spring:
  application:
    name: admin-server

#Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: "*"
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: ALWAYS

# info信息会显示到SpringBootAdmin的server端，这里取的是pom文件中的数据
info:
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@